apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram-primary
    receivers:
      - uid: telegram_primary
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: "$GRAFANA_ALERT_TELEGRAM_BOT_TOKEN"
          chatid: "$${GRAFANA_ALERT_TELEGRAM_CHAT_ID}"
          parse_mode: "Markdown"
          disable_notification: false
          protect_content: false

